# Generated by Django 3.2.7 on 2021-09-17 20:58

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('isAdmin', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions', models.TextField()),
                ('opening_date', models.DateTimeField()),
                ('closing_date', models.DateTimeField()),
                ('caste', models.CharField(choices=[('SCT', 'SC/ST'), ('OBC', 'OBC'), ('GEN', 'General')], max_length=3)),
                ('program', models.CharField(choices=[('B', 'BTech'), ('M', 'MTech'), ('P', 'PhD')], max_length=1)),
                ('department', models.CharField(choices=[('BIO', 'BioTech'), ('CHE', 'Chemical'), ('CIV', 'Civil'), ('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('MEC', 'Mechanical')], max_length=3)),
                ('specialization', models.CharField(blank=True, choices=[('MET', 'Metallurgical'), ('POW', 'Power'), ('COM', 'Communications'), ('ENV', 'Environmental')], max_length=3)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('cgpa', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('isAdmin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=None)),
                ('caste', models.CharField(choices=[('SCT', 'SC/ST'), ('OBC', 'OBC'), ('GEN', 'General')], max_length=3)),
                ('program', models.CharField(choices=[('B', 'BTech'), ('M', 'MTech'), ('P', 'PhD')], max_length=1)),
                ('department', models.CharField(choices=[('BIO', 'BioTech'), ('CHE', 'Chemical'), ('CIV', 'Civil'), ('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('MEC', 'Mechanical')], max_length=3)),
                ('specialization', models.CharField(blank=True, choices=[('MET', 'Metallurgical'), ('POW', 'Power'), ('COM', 'Communications'), ('ENV', 'Environmental')], max_length=3)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('cgpa', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.scholarship')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
            options={
                'ordering': ['-applied'],
            },
        ),
    ]
